export enum ApiEndPoint {
  login = "api/Users/Login",
  ImageUpload = "api/Upload/UploadProfilePic",
  categoryImageUpload = "api/Upload/UploadProductCategoryImage",

  // for notification 
  tockenFcm = 'api/Notification/updateFCMToken',
  getNotifactionsList = 'api/Notification/getNotificationList',
  broadcastNotification = "api/Notification/getBroadcastNotificationList",
  addbroadcastNotification = "api/Notification/broadcastNotification",
  deleteBroadcastNotification = "api/Notification/deleteBroadcastNotification",
  getReadNotiction = 'api/Notification/readNotification',
  getNotifictionCount = 'api/Notification/getNotificationCount',
  deleteAllNotification = 'api/Notification/deleteNotification',

  // Add Vendor Form Api 
  getCountry = "api/Content/GetCountries",
  getState = "api/Content/GetStates",
  addVendor = "api/Admin/AddVendor",
  getPlanList = "api/Admin/getMembershipPlanList",
  addUpdatePlan = "/api/Admin/addUpdateMembershipPlan",
  getPlanDetail = "api/Admin/getMembershipPlanDetail",
  deleteAddedPlan = "api/Admin/deleteMembershipPlan",
  updatePlan = "/api/Admin/addUpdateMembershipPlan",
  UpdateVendor = "api/Admin/UpdateVendor",
  vendorList = "api/Admin/GetVendorList",
  vendorDetail = "api/Admin/GetVendorDetail",
  vendorStatus = "api/Admin/SetVendorStatus",
  AdminUserList = "api/Admin/GetAdminUserList",
  AdminUserDetail = "api/Admin/GetAdminUserDetail",
  AddAdminUser = "api/Admin/AddAdminUser",
  UpdateAdminUser = "api/Admin/UpdateAdminUser",
  deleteVendor = "api/Admin/DeleteVendor",
  deleteAdminUser = "api/Admin/DeleteAdminUser",
  getcategoryList = "api/Category/GetProductCategoryList",
  getcategoryListSuper = "api/Vendor/GetVendorProductCategoryList",
  getcategoryVendor = "api/Vendor/GetVendorProductCategoryList",
  getProductCategoryRequestList = "api/Category/GetProductCategoryRequests",
  acceptRejectCategory = "/api/Category/SetCategoryStatus",
  categoryStatus = "api/Vendor/SetVendorCategoryStatus",
  addCategory = "api/Category/AddProductCategory",
  updateCategory = "api/Category/UpdateProductCategory",
  categoryDetail = "api/Category/GetProductCategoryDetail",
  deleteMainCategory = "api/Category/DeleteProductCategory",
  deleteSubCategory = "api/Category/DeleteProductCategory",
  addBrand = "api/Brand/AddBrand",
  updateBrand = "api/Brand/UpdateBrand",
  deleteBrand = "api/Brand/DeleteBrand",
  brandDetail = "api/Brand/GetBrandDetail",
  brandImage = "api/Upload/UploadBrandImage",
  QRImage = "/api/Upload/UploadQRCode",
  getBrandList = "api/Brand/GetBrandList",
  getBannerList = "api/Content/GetBannerList",
  getBannerDetail = "api/Content/GetBannerDetail",
  addBanner = "api/Admin/AddBanner",
  updateBanner = "api/Admin/UpdateBanner",
  deleteHomeBanners = "api/Admin/DeleteBanner",
  productContainerType = "api/Content/GetProductContainerTypeList",
  productQunatity = "api/Content/GetProductQuantityTypeList",
  addProduct = "api/Product/AddProduct",
  updateProduct = "api/Product/UpdateProduct",
  productImage = "api/Upload/UploadProductImage",
  shopImage = "api/Upload/UploadShopImage",
  getShopBannerList = "api/Vendor/GetShopBannerList",
  deleteShopBanners = "api/Vendor/DeleteShopBanner",
  postStatus = "api/Product/SetProductStatus",
  productList = "api/Product/GetProductList",
  additionalProduct = "api/Vendor/GetProductList",
  additionalProductList = "api/Vendor/GetAdditionalProductList",
  productStock = "api/Product/updateBasicProductInfo",
  deleteProduct = "api/Product/DeleteProduct",
  addShopBanner = "api/Vendor/AddShopBanner",
  updateShopBanner = "api/Vendor/UpdateShopBanner",
  getShopBannerDetail = "api/Vendor/GetShopBannerDetail",
  getCollectionList = "api/Product/GetCollectionList",
  getCollectionNameList = "api/Product/GetCollectionNameList",
  productDetail = "api/Product/GetProductDetail",
  productInventoryDetail = "api/Product/GetInventoryProductDetail",
  getCollectionDetail = "api/Product/GetCollectionDetail",
  addCollection = "api/Product/AddCollection",
  collectionImage = "api/Upload/UploadCollectionImage",
  deleteCollection = "api/Product/DeleteCollection",
  orderList = "api/Vendor/GetVendorOrderList",
  orderListFilter = "api/Vendor/GetVendorOrderList",
  orderdetail = "api/Vendor/GetVendorOrderDetail",
  orderStatus = "api/Vendor/SetOrderStatus",
  paymentStatus = "api/Vendor/SetPaymentStatus",
  superProfile = "UpdateSuperAdminDetail",
  superProfileDetail = "api/Admin/GetSuperAdminDetail",
  postSuperAdmimProfile = "/api/Admin/UpdateSuperAdminDetail",
  additionalList = "/api/Vendor/GetAdditionalProductList",
  addeditAdditional = "/api/Vendor/AddUpdateAdditionalProduct",
  deleteAdditional = "/api/Vendor/DeleteAdditionalProduct",
  deliveryStatus = "api/Vendor/SetDeliveryManStatus",
  // payment
  buyPlan = "api/Vendor/buyMembershipPlan",
  paymentOPtion = "api/Admin/GetPaymentOptions",
  base64 = "api/Product/GetProductImageInBase64",
  uploadReceipt = "api/Upload/UploadPaymentReceipt",
  transictionId = "api/Vendor/GetMembershipDetailByTransactionId",

  // Distributor 

  distributorList = "api/Admin/GetDistributorList",
  distributorAdd = "api/Admin/AddDistributor",
  distributorDetail = "api/Admin/GetDistributorDetail",
  updateDistributor = "api/Admin/UpdateDistributor",

  // Product Inventory 

  productInventoryList = "api/Product/GetInventoryProductList",
  deleteProductInventory = "api/Product/DeleteProductFromInventory",
  addProductInventory = "api/Product/AddProductToInventory",
  inventoryBase64 = "api/Product/GetProductImageInBase64",
  productInventoryUpdate = "api/Product/UpdateProductToInventory",
  distributorVendorList = "api/Admin/GetVendorList",
  updateUserAdmin = "api/Admin/UpdateAdminUser",

  // Earning

  getEarningList = "api/Admin/GetDistributorEarning",
  // image link 
  redirect = "https://api.phonepe.com/apis/hermes/pg/v1/pay",
  imageLink = "api/Upload/GenerateImageLinkInBulk",
  linkList = "api/Upload/GetGenerateImageLinks",
  getExcelSteet = "api/Vendor/GetExcelForBulkUpload",
  excelUpload = "api/Vendor/UploadExcelForBulkUpload",

  /** Vendor Dairy Info **/
  getDairyInformation = "api/Vendor/GetDairyInfo",
  updateDairyInfo = "api/Vendor/AddUpdateDairyInfo",
  addDairyInfo = "api/Vendor/AddUpdateDairyInfo",

  // Area
  areaList = "api/Vendor/GetAreaCodeList",
  addarea = "api/Vendor/AddUpdateAreaCode",
  deleteArea = "api/Vendor/DeleteAreaCode",
  areaDetail = "api/Vendor/GetAreaCodeDetail",
  getCustomerList = "api/Vendor/GetCustomerList",
  getCustomerDetail = "api/Vendor/GetCustomerDetail",
  getCustomerListOffline = "api/Vendor/GetVendorCustomerList",
  addCustomer ="api/Vendor/AddUpdateVendorCustomer",
  getCustomerListOfflineDetail = "api/Vendor/GetVendorCustomerDetail",
  getCustomerListOfflineDelete = "api/Vendor/DeleteVendorCustomer",
  setCustomerAreaCode = "api/Vendor/SetAreaCodeForCustomer",
  getTopUpList = "api/Vendor/GetDairyTopUpList",
  postDairyWalletStatus = "api/Vendor/SetDairyWalletStatus",
  getDeliveryManList = "api/Vendor/GetDeliveryManList",
  getAssignOrderToDeliveryManList = "api/Vendor/GetDeliveryManAssignedOrderList",
  postDairyMan = "api/Vendor/AddUpdateDeliveryMan",
  getDeliveryManDetail = "api/Vendor/GetDeliveryManDetail",
  getDeliveryManOrderDetail = "api/Vendor/GetDeliveryManAssignedOrderDetail",
  updateDeliveryMan = "api/Vendor/AddUpdateDeliveryMan",
  deleteAddedDeliveryMan = "api/Vendor/DeleteDeliveryMan",
  subscriptionList = "api/Vendor/GetSubscriptionList",
  subscriptionDetail = "api/Vendor/GetSubscriptionDetail",
 
  // Payment

  payment = "api/Vendor/InitiatePaymentRequest",
  checkPayment = "api/Vendor/CheckPaymentStatus",
  counterMessage = "api/Admin/getVendorSuscriptionAlertMessage",
  timeStatus = "api/Vendor/SetShopStatus",



}
